name: JIRA Connection


on: [push]

jobs:
  enforce-issue:
    runs-on: ubuntu-latest
    name: JIRA Association
    steps:
      - name: Check for JIRA ISSUE
        id: check
        uses: supplypike/jira-pr-link-action@v1
        with:
          ignore-author: dependabot[bot]
          project: "SRENEW"
