name: JIRA Connection

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  enforce-issue:
    runs-on: ubuntu-latest
    name: JIRA Association
    steps:
    - name: Autosquash
      uses: tibdex/autosquash@v2.2.2
    - uses: actions/checkout@v1
    - uses: dylanvann/check-pull-request-title@v1
      with:
          # Match pull request titles in the form UI-1234 - Message.
          pattern: '^UI-\d* - '

#       - name: Check for JIRA ISSUE
#         id: check
#         uses: harmanjot78/jira-pr-link-action@v1
#         with:
#           ignore-author: dependabot[bot]
#           project: "T1"
#           issue: "T1-3"
